#!/bin/bash

#cmake -S ./ -B build/Release -DCMAKE_BUILD_TYPE=Release
#cmake --build build/Release
#./build/Release/HashTable

cmake -S ./ -B build/Debug -DCMAKE_BUILD_TYPE=Debug
cmake --build build/Debug
#valgrind --tool=callgrind ./build/Debug/HashTable --crc32_intrinsic
./build/Debug/HashTable --crc32
