#!/bin/bash

cmake -S ./ -B build/Release -DCMAKE_BUILD_TYPE=Release
cmake --build build/Release
./build/Release/HashTable --crc32_asm

# cmake -S ./ -B build/Debug -DCMAKE_BUILD_TYPE=Debug
# cmake --build build/Debug
# ./build/Debug/HashTable --crc32_asm

# valgrind --tool=callgrind ./build/Debug/HashTable --crc32_asm
# perf record -F 99 -g ./build/Debug/HashTable --crc32_asm
# objdump -D -M intel build/Debug/HashTable
